name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      push_latest:
        description: "同时推送 latest 标签"
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/opaonio
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest,enable=${{ github.event.inputs.push_latest == 'true' }}
            type=sha,format=short
            type=ref,event=tag
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=opaonio
            org.opencontainers.image.description=Multi-arch image for opaonio (amd64/arm64/arm/v7)
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ssZ'}}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # 一次性产出 amd64/arm64/armv7
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 缓存显著加速后续构建
          cache-from: type=gha
          cache-to: type=gha,mode=max
